### ISSUE TITLE
Are the 3 main manuals representing the main building blocks of the nix ecosystem?

### ISSUE THREAD

**Issue by olafklingt** [NixOS/nix-book#10]
Looking at [this diagram outlining the book project](https://github.com/NixOS/nix-book#a-vision-for-the-journey-into-nix-nixpkgs-and-nixos) I find the current 3 manuals at the bottom. 
I am brainstorming here about two different main angles to look at the 
I like to suggest that they do not represent well the different layers that define the nix ecosystem.

A. technical layers (ordered roughly by scope):
1. nix-package-manager (setup nix)
2. nix-cli (type in the shell)
3. nix-language (write nix)
4. language-standards (lib.functions, pkgs, modules, overlays, system-configurations, flakes) (use nix)
5. nix-tools like home-manager, nixOps, deam2nix ...  (use extended nix)
6. NixOS (setup nixos)

B. user-types (ordered roughly by use-case complexity):
users, nix-contributors, developers, DevOps/deployers

Every technical layer (A) can be described for every user-type (B) with a different depth.
It could be used to develop a basic two level hierarchy to structure the content of the 3 current books.

**Comment by olafklingt** [comment]
(an additional comment that should not distract from the main issue)

I am not really sure where to put:
1. shells, vms, containers ...
  - part of language-standards in so far as the definitions need to contain specific content
  - part of nix-cli
2. remote deployment, caching ...
  - part of nix-cli
  - part of nix-tools (NixOps)
  - part of NixOS (some functionality depends on nixos installation as far  as i understand)

I am not really sure if DevOps is a user-type or simply an advanced user.

**Comment by fricklerhandwerk** [comment]
>  It could be used to develop a basic two level hierarchy to structure the content of the 3 current books.

Maybe there is a misunderstanding. The "book" idea is to collect all instruction-style material in a central place and [clean up the manuals to be only reference-style](https://github.com/NixOS/nix-book/blob/2208ba2162bd102aaa9bc166be76c6925da45919/README.md?plain=1#L193) (possibly to the point of being entirely automatically derived from the code).

> A. technical layers (ordered roughly by scope):
> 1. nix-package-manager (setup nix)
> 2. nix-cli (type in the shell)
> 3. nix-language (write nix)
> 4. language-standards (lib.functions, pkgs, modules, overlays, system-configurations, flakes) (use nix)
> 5. nix-tools like home-manager, nixOps, deam2nix ...  (use extended nix)
> 6. NixOS (setup nixos)

That sounds a lot like the learning curve proposed in the diagram, except that the diagram allows multiple independent paths after learning the Nix language. Am I missing some fundamental difference in your suggestion?

> Every technical layer (A) can be described for every user-type (B) with a different depth.

That's what is intended for more complex tasks by ordering the individual sections within a chapter by sophistication. I don't think there should be multiple levels of detail, already because that does not sound maintainable. Keeping sections small and linked should allow looking up more advanced use cases on demand, after learning the more basic ones in sequence.

> I am not really sure where to put: remote deployment, caching ...

That needs more clarification indeed, especially regarding prerequisite knowledge.

**Comment by olafklingt** [comment]
I overlooked the "reference style" function of the current manuals in the plan.
I think there are some gaps in the diagram I will try to extend the diagram.
The mentioned layers and user-types might be more of a tool to evaluate the manual.
