### ISSUE TITLE
establish writing standards

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix-book#18]
- [proposal](https://github.com/NixOS/nix-book/blob/2208ba2162bd102aaa9bc166be76c6925da45919/CONTRIBUTING.md#guidelines)
- collect requirements from experience

**Comment by asymmetric** [comment]
I think part of the writing standard should be identifying the target audience. The nixpkgs manual has the [infamous natural deduction proof](https://nixos.org/manual/nixpkgs/stable/#ssec-stdenv-dependencies), which IME helps very few people understand the difference between e.g. `buildInputs` and `nativeBuildInputs`.

What kind of languge should the documentation use? What kind of prerequisite knowledge do we assume?

So maybe in addition to kind and concise, the documentation should be.. clear? exhaustive?

**Comment by TLATER** [comment]
So I've been [drafting up a prelude to the package management chapter](https://discourse.nixos.org/t/depreciate-the-use-of-nix-env-to-install-packages/20139/5?u=tlater). The current guidelines are very helpful already, hat off to you @fricklerhandwerk, looking forward to having my writing reviewed by you :)

I'll share a PR when I'm done, but in the mean time let me note some things:

- Let's stick to second person? I find this helps a lot in staying friendly, and thinking about the person I am writing for.
  - [The Rust book](https://doc.rust-lang.org/stable/book/ch00-00-introduction.html) (which we've all read, I'm sure) uses second person too, and it's probably one of the single best pieces of documentation I've ever read, so I don't think this should be controversial, but I do want to clarify this, and the choice should probably be recorded.
- Capitalize Nix? NixOS? nixpkgs?
- I'm assuming someone with no experience with even Debian for the moment. I'm doing so because the current prerequisite list for this chapter doesn't include any Linux experience.
  - I think per-chapter prerequisites are indeed an excellent way of managing expectations here. We can even link some external resources to help get people up to speed on those prerequisites.
  - Problems: Do I need to explain terminals? Text files? Should we have a separate document that lets someone go from downloaded ISO -> ready to read the book? I guess we can expect the average reader will have used a computer before, so explaining software is probably going too far.
- I've been adding notes around NixOS as well. I think it's reasonable to assume a lot of people read this book while trying to understand NixOS. NixOS-related topics, while sometimes distinct, are by nature intermingled with the general topics. Do we need a separate Nix-on-Mac or Nix-on-Ubuntu "book" that covers similar content?
  - I'm hesitant to make the chapters complex by having bits of content specific to environments. Maybe info boxes?

**Comment by fricklerhandwerk** [comment]
> Capitalize Nix? NixOS? nixpkgs? Heading Case?

See https://github.com/nix-dot-dev/nix.dev/pull/263 - use the proposal in the PR until then.

> Let's stick to second person?

I recently read @zimbatm's [considerations on that](https://zimbatm.com/notes/writing#acde3e456f5e4ce5af650f26ecc225ff) and would like to go in that direction. That is, be descriptive, and use second person when the reader is to be addressed, e.g. for direct instructions.

Suggestion for general use: https://github.com/nix-dot-dev/nix.dev/pull/264

> the current prerequisite list for this chapter doesn't include any Linux experience. 

That is not fleshed out yet. The general prerequisites should be some proficiency with the command line, but nothing specific to any distribution. Right now it must suffice to just state what is expected to be known, as as finding useful resources is very tedious. Of course link to previous chapters when we have them.

> Should we have a separate document that lets someone go from downloaded ISO -> ready to read the book?

Let us assume general Linux understanding for now. Everything else is too much to tackle.

Noted here: https://github.com/nix-dot-dev/nix.dev/pull/265

> I think it's reasonable to assume a lot of people read this book while trying to understand NixOS

I want to stress that the goal right now is to teach basic Nix usage without taking NixOS into consideration, yet. It should both focus our efforts on something achievable and also fix the huge issue of people confusing Nix package manager and NixOS. 

Just as we have to make clear the distinction between imperative and declarative package management, we should make clear the distinction between Nix package manager and NixOS, and encourage people to try Nix on their existing system before hitting the brick wall of a learning curve with NixOS, even if they are enthusiastic to dive in.

> It would be nice to have some people around who are practiced in identifying words and phrases that may trip up English speakers with more limited vocabulary.

Yes.

@TLATER Feel free to add more PRs to the contributing guide on nix.dev if you want to see more clarifications, we can iterate from there. (We decided to move efforts over to nix.dev, see [docs team meeting #4](https://discourse.nixos.org/t/2022-07-07-documentation-team-meeting-notes-4/20198)).
